/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 258341a0a17e4b69b6380ac4d87b4bf7)
interface __BaseEnv_Env {
	HOSTS: KVNamespace;
	ROUTER_KEY: SecretsStoreSecret;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
