/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f9556d0d9162335737680ba8bbf0951b)
interface __BaseEnv_Env {
	HOSTS: KVNamespace;
	ROUTER_KEY: SecretsStoreSecret;
	AUTH_RATE_LIMIT: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
