/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7ce7a45fce2ecb312875319dd65f2af4)
interface __BaseEnv_Env {
	HOSTS: KVNamespace;
	ROUTER_KEY: SecretsStoreSecret;
	AUTH_RATE_LIMIT: RateLimit;
	GUEST_RATE_LIMIT: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
