/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KitRouteImport } from './routes/kit'
import { Route as AppsAppScreensScreenRouteImport } from './routes/apps.$app.screens.$screen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppScreensScreenRoute = AppsAppScreensScreenRouteImport.update({
  id: '/apps/$app/screens/$screen',
  path: '/apps/$app/screens/$screen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kit': typeof KitRoute
  '/apps/$app/screens/$screen': typeof AppsAppScreensScreenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kit': typeof KitRoute
  '/apps/$app/screens/$screen': typeof AppsAppScreensScreenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kit': typeof KitRoute
  '/apps/$app/screens/$screen': typeof AppsAppScreensScreenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kit' | '/apps/$app/screens/$screen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kit' | '/apps/$app/screens/$screen'
  id: '__root__' | '/' | '/kit' | '/apps/$app/screens/$screen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KitRoute: typeof KitRoute
  AppsAppScreensScreenRoute: typeof AppsAppScreensScreenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$app/screens/$screen': {
      id: '/apps/$app/screens/$screen'
      path: '/apps/$app/screens/$screen'
      fullPath: '/apps/$app/screens/$screen'
      preLoaderRoute: typeof AppsAppScreensScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KitRoute: KitRoute,
  AppsAppScreensScreenRoute: AppsAppScreensScreenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
