/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ReleasesIndexRouteImport } from './routes/releases/index'
import { Route as ReleasesReleaseIdRouteImport } from './routes/releases/$releaseId'
import { Route as ReleasesDiffRouteImport } from './routes/releases/diff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesReleaseIdRoute = ReleasesReleaseIdRouteImport.update({
  id: '/releases/$releaseId',
  path: '/releases/$releaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesDiffRoute = ReleasesDiffRouteImport.update({
  id: '/releases/diff',
  path: '/releases/diff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/releases/diff': typeof ReleasesDiffRoute
  '/releases/': typeof ReleasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/releases/diff': typeof ReleasesDiffRoute
  '/releases': typeof ReleasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/releases/diff': typeof ReleasesDiffRoute
  '/releases/': typeof ReleasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/releases/$releaseId'
    | '/releases/diff'
    | '/releases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/releases/$releaseId'
    | '/releases/diff'
    | '/releases'
  id:
    | '__root__'
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/releases/$releaseId'
    | '/releases/diff'
    | '/releases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  ReleasesReleaseIdRoute: typeof ReleasesReleaseIdRoute
  ReleasesDiffRoute: typeof ReleasesDiffRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/': {
      id: '/releases/'
      path: '/releases'
      fullPath: '/releases/'
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$releaseId': {
      id: '/releases/$releaseId'
      path: '/releases/$releaseId'
      fullPath: '/releases/$releaseId'
      preLoaderRoute: typeof ReleasesReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/diff': {
      id: '/releases/diff'
      path: '/releases/diff'
      fullPath: '/releases/diff'
      preLoaderRoute: typeof ReleasesDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  ReleasesReleaseIdRoute: ReleasesReleaseIdRoute,
  ReleasesDiffRoute: ReleasesDiffRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
