/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e4af0ee312b88f606fc5f09b00f16244)
interface __BaseEnv_Env {
	DB: D1Database;
	AUDIT_QUEUE: Queue;
	LOADER: WorkerLoader;
	CAPABILITY_SIGNING_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CAPABILITY_SIGNING_KEY">> {}
}
