/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 62e8b27e9d1e93e5a018af91b8e73213)
interface __BaseEnv_Env {
	ROUTER_HOSTS: KVNamespace;
	RELEASES: R2Bucket;
	DB: D1Database;
	TENANT_ADMIN_TOKEN: SecretsStoreSecret;
	DEPLOYER_API_TOKEN: SecretsStoreSecret;
	ROUTER_KEY: SecretsStoreSecret;
	CLIENT_KEY: SecretsStoreSecret;
	ENTRA_CLIENT_SECRET: SecretsStoreSecret;
	MICROSOFT_CLIENT_SECRET: SecretsStoreSecret;
	GOOGLE_CLIENT_SECRET: SecretsStoreSecret;
	COMPOSIO_API_KEY: SecretsStoreSecret;
	PROVISION_CLIENT: Workflow<Parameters<import("./src/server").ProvisionClient['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
