/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2c8e9a6a7c1475996fdf1dc3ff637797)
interface __BaseEnv_Env {
	RELEASES: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
