/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7daec83279dbd129bfb50271143858cd)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	DB: D1Database;
	KNOWLEDGE: D1Database;
	EMAIL: SendEmail;
	AUDIT_QUEUE: Queue;
	LOADER: WorkerLoader;
	AI: Ai;
	ASSETS: Fetcher;
	ROUTER_SECRET: string;
	WORKSPACES: DurableObjectNamespace<import("./src/index").Workspace>;
	APPS: DurableObjectNamespace<import("./src/index").App>;
	AUDIT_LOG: DurableObjectNamespace<import("./src/index").AuditLog>;
	CONNECT: Fetcher /* grasp-os-connect */;
	WORKFLOWS: Workflow<Parameters<import("./src/index").WorkflowDispatcher['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Workspace" | "App" | "AuditLog";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ROUTER_SECRET">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}