/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 30809a7c2b0f6061e9c831027523e79c)
interface __BaseEnv_Env {
	KV: KVNamespace;
	FILES: R2Bucket;
	DB: D1Database;
	KNOWLEDGE: D1Database;
	EMAIL: SendEmail;
	AUDIT_QUEUE: Queue;
	LOADER: WorkerLoader;
	AI: Ai;
	WORKSPACES: DurableObjectNamespace<import("./src/index").Workspace>;
	APPS: DurableObjectNamespace<import("./src/index").App>;
	AUDIT_LOG: DurableObjectNamespace<import("./src/index").AuditLog>;
	CONNECT: Fetcher /* grasp-os-connect */;
	WORKFLOWS: Workflow<Parameters<import("./src/index").WorkflowDispatcher['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Workspace" | "App" | "AuditLog";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.sql" {
	const value: string;
	export default value;
}