/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --config=../connect/wrangler.jsonc --include-runtime=false` (hash: 8a7b578de47ca59f42fd696076e4b325)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	DB: D1Database;
	KNOWLEDGE: D1Database;
	EMAIL: SendEmail;
	AUDIT_QUEUE: Queue;
	AUDIT_DLQ: Queue;
	LOADER: WorkerLoader;
	AI: Ai;
	ASSETS: Fetcher;
	ROUTER_SECRET: string;
	BETTER_AUTH_SECRET: string;
	CAPABILITY_SIGNING_KEY: string;
	WORKSPACES: DurableObjectNamespace<import("./src/index").Workspace>;
	APPS: DurableObjectNamespace<import("./src/index").App>;
	AUDIT_LOG: DurableObjectNamespace<import("./src/index").AuditLog>;
	CONNECT: Service<typeof import("../connect/src/index").default>;
	WORKFLOWS: Workflow<Parameters<import("./src/index").WorkflowDispatcher['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Workspace" | "App" | "AuditLog";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ROUTER_SECRET" | "BETTER_AUTH_SECRET" | "CAPABILITY_SIGNING_KEY">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}